import { DEMO_BUSINESS_ID, ZQX_BUSINESS_ID, type Records } from "@/lib/core/types";

const now = "2026-04-29T14:00:00.000Z";

export const seedRecords: Records = {
  businesses: [
    {
      id: ZQX_BUSINESS_ID,
      created_at: now,
      updated_at: now,
      name: "ZQX Consulting",
      slug: "zqx-consulting",
      industry: "consulting",
      contact_email: "gvcotto@zqxconsulting.com",
      logo_url: "/logos/zqx.svg",
      status: "active",
      notes: "Cuenta administradora de la plataforma y coordinacion comercial.",
    },
    {
      id: DEMO_BUSINESS_ID,
      created_at: now,
      updated_at: now,
      name: "Clinica Dental Smile",
      slug: "clinica-dental-smile",
      industry: "dentist",
      contact_email: "admin@dentalsmile.example",
      logo_url: "/logos/dental-smile.svg",
      status: "active",
      notes: "Clínica dental con flujo de recepción, agenda y control de cobros.",
    },
    {
      id: "biz-university-demo",
      created_at: now,
      updated_at: now,
      name: "Universidad Central",
      slug: "universidad-central",
      industry: "university",
      contact_email: "ops@universitydemo.example",
      logo_url: "/logos/universidad-central.svg",
      status: "active",
      notes: "Operación de admisiones con entrevistas, becas y seguimiento académico.",
    },
    {
      id: "biz-food-demo",
      created_at: now,
      updated_at: now,
      name: "Mesa Central Foods",
      slug: "mesa-central-foods",
      industry: "restaurant",
      contact_email: "reservas@mesacentral.example",
      logo_url: "/logos/mesa-central-foods.svg",
      status: "active",
      notes: "Gestion de reservas, eventos privados y pedidos corporativos.",
    },
  ],
  users: [
    {
      id: "usr-zqx-owner",
      created_at: now,
      updated_at: now,
      business_id: ZQX_BUSINESS_ID,
      email: "gvcotto@zqxconsulting.com",
      name: "G. V. Cotto",
      role: "zqx_owner",
      status: "active",
      temporary_password: "ZQXdemo2026!",
      auth_source: "local",
    },
    {
      id: "usr-dental-admin",
      created_at: now,
      updated_at: now,
      business_id: DEMO_BUSINESS_ID,
      email: "admin@dentalsmile.example",
      name: "Dental Smile Admin",
      role: "business_admin",
      status: "active",
      temporary_password: "DemoDental2026!",
      auth_source: "local",
    },
    {
      id: "usr-university-admin",
      created_at: now,
      updated_at: now,
      business_id: "biz-university-demo",
      email: "ops@universitydemo.example",
      name: "Universidad Central Admin",
      role: "business_admin",
      status: "active",
      temporary_password: "DemoUniversity2026!",
      auth_source: "local",
    },
    {
      id: "usr-food-admin",
      created_at: now,
      updated_at: now,
      business_id: "biz-food-demo",
      email: "reservas@mesacentral.example",
      name: "Mesa Central Admin",
      role: "business_admin",
      status: "active",
      temporary_password: "DemoFood2026!",
      auth_source: "local",
    },
  ],
  modules: [
    {
      id: "mod-general",
      created_at: now,
      updated_at: now,
      key: "general",
      name: "Módulo general",
      description: "CRM base con clientes, citas, servicios, seguimientos, pagos, FAQ y chatbot.",
    },
    {
      id: "mod-dentist",
      created_at: now,
      updated_at: now,
      key: "dentist",
      name: "Módulo dental",
      description: "Pacientes, agenda por sillón, intake, recordatorios, recalls y reputación.",
    },
    {
      id: "mod-medical",
      created_at: now,
      updated_at: now,
      key: "medical",
      name: "Módulo médico",
      description: "Pacientes, citas, servicios clínicos, seguimientos y cobros.",
    },
    {
      id: "mod-university",
      created_at: now,
      updated_at: now,
      key: "university",
      name: "Módulo universitario",
      description: "Admisiones, estudiantes, asesoría académica, becas y seguimiento.",
    },
    {
      id: "mod-consulting",
      created_at: now,
      updated_at: now,
      key: "consulting",
      name: "Módulo consultoría",
      description: "Cuentas, discovery, pipeline comercial, entregables y revisiones.",
    },
    {
      id: "mod-restaurant",
      created_at: now,
      updated_at: now,
      key: "restaurant",
      name: "Módulo comida",
      description: "Reservas, pedidos corporativos, eventos, clientes recurrentes y cobros.",
    },
    {
      id: "mod-custom",
      created_at: now,
      updated_at: now,
      key: "custom",
      name: "Módulo personalizado",
      description: "Workflows, etiquetas y automatizaciones configurables por industria.",
    },
  ],
  business_modules: [
    {
      id: "bmod-zqx-general",
      created_at: now,
      updated_at: now,
      business_id: ZQX_BUSINESS_ID,
      module_id: "mod-general",
      enabled: true,
      configuration: { default: true },
    },
    {
      id: "bmod-zqx-consulting",
      created_at: now,
      updated_at: now,
      business_id: ZQX_BUSINESS_ID,
      module_id: "mod-consulting",
      enabled: true,
      configuration: { account_label: "Cuentas" },
    },
    {
      id: "bmod-dental-general",
      created_at: now,
      updated_at: now,
      business_id: DEMO_BUSINESS_ID,
      module_id: "mod-general",
      enabled: true,
      configuration: { default: true },
    },
    {
      id: "bmod-dental-dentist",
      created_at: now,
      updated_at: now,
      business_id: DEMO_BUSINESS_ID,
      module_id: "mod-dentist",
      enabled: true,
      configuration: { patient_label: "Pacientes", appointment_label: "Citas dentales", reminder_sequence: "48-24-1" },
    },
    {
      id: "bmod-university-general",
      created_at: now,
      updated_at: now,
      business_id: "biz-university-demo",
      module_id: "mod-general",
      enabled: true,
      configuration: { default: true },
    },
    {
      id: "bmod-university-module",
      created_at: now,
      updated_at: now,
      business_id: "biz-university-demo",
      module_id: "mod-university",
      enabled: true,
      configuration: { student_label: "Estudiantes" },
    },
    {
      id: "bmod-food-general",
      created_at: now,
      updated_at: now,
      business_id: "biz-food-demo",
      module_id: "mod-general",
      enabled: true,
      configuration: { default: true },
    },
    {
      id: "bmod-food-restaurant",
      created_at: now,
      updated_at: now,
      business_id: "biz-food-demo",
      module_id: "mod-restaurant",
      enabled: true,
      configuration: { reservation_label: "Reservas" },
    },
  ],
  clients: [
    {
      id: "cli-zqx-dental-smile",
      created_at: now,
      updated_at: now,
      business_id: ZQX_BUSINESS_ID,
      name: "Clinica Dental Smile",
      type: "organization",
      email: "admin@dentalsmile.example",
      phone: "+502 5555 0100",
      status: "active",
      service_interest: "Blueprint dental CRM",
      notes: "Cuenta configurada para agenda, intake, recordatorios y reputacion.",
    },
    {
      id: "cli-zqx-university",
      created_at: now,
      updated_at: now,
      business_id: ZQX_BUSINESS_ID,
      name: "Universidad Central",
      type: "organization",
      email: "ops@universitydemo.example",
      phone: "+502 5555 0190",
      status: "prospect",
      service_interest: "Admissions CRM",
      notes: "Necesita flujo de admisiones y seguimiento de becas.",
    },
    {
      id: "cli-maria-lopez",
      created_at: now,
      updated_at: now,
      business_id: DEMO_BUSINESS_ID,
      name: "Maria Lopez",
      type: "person",
      email: "maria.lopez@example.com",
      phone: "+502 5555 0101",
      status: "active",
      service_interest: "Limpieza dental",
      notes: "Prefiere recordatorios por WhatsApp. Recall preventivo cada 6 meses.",
    },
    {
      id: "cli-carlos-herrera",
      created_at: now,
      updated_at: now,
      business_id: DEMO_BUSINESS_ID,
      name: "Carlos Herrera",
      type: "person",
      email: "carlos.herrera@example.com",
      phone: "+502 5555 0102",
      status: "prospect",
      service_interest: "Evaluación de ortodoncia",
      notes: "Interesado en opciones de financiamiento antes de confirmar tratamiento.",
    },
    {
      id: "cli-sofia-mendez",
      created_at: now,
      updated_at: now,
      business_id: DEMO_BUSINESS_ID,
      name: "Sofía Méndez",
      type: "person",
      email: "sofia.mendez@example.com",
      phone: "+502 5555 0104",
      status: "lead",
      service_interest: "Consulta de urgencia",
      notes: "Llegó desde formulario web. Requiere respuesta el mismo día.",
    },
    {
      id: "cli-university-demo",
      created_at: now,
      updated_at: now,
      business_id: "biz-university-demo",
      name: "Ana Ramírez",
      type: "person",
      email: "ana.ramirez@example.edu",
      phone: "+502 5555 0103",
      status: "lead",
      service_interest: "Entrevista de admisión",
      notes: "Consulta capturada desde chatbot.",
    },
    {
      id: "cli-university-luis",
      created_at: now,
      updated_at: now,
      business_id: "biz-university-demo",
      name: "Luis Morales",
      type: "person",
      email: "luis.morales@example.edu",
      phone: "+502 5555 0144",
      status: "active",
      service_interest: "Revisión de becas",
      notes: "Pendiente de documentos financieros.",
    },
    {
      id: "cli-food-andrea",
      created_at: now,
      updated_at: now,
      business_id: "biz-food-demo",
      name: "Andrea Castillo",
      type: "person",
      email: "andrea.castillo@example.com",
      phone: "+502 5555 0180",
      status: "active",
      service_interest: "Reserva de mesa",
      notes: "Cliente recurrente. Solicita mesa cerca de ventana.",
    },
    {
      id: "cli-food-corp",
      created_at: now,
      updated_at: now,
      business_id: "biz-food-demo",
      name: "Grupo Alimentos GT",
      type: "organization",
      email: "eventos@alimentosgt.example",
      phone: "+502 5555 0181",
      status: "prospect",
      service_interest: "Evento privado",
      notes: "Cotizar menú para 35 personas.",
    },
  ],
  services: [
    {
      id: "svc-zqx-dental-blueprint",
      created_at: now,
      updated_at: now,
      business_id: ZQX_BUSINESS_ID,
      name: "Blueprint dental CRM",
      category: "Consultoria",
      price: 1200,
      duration_minutes: 90,
      active: true,
    },
    {
      id: "svc-zqx-workflows",
      created_at: now,
      updated_at: now,
      business_id: ZQX_BUSINESS_ID,
      name: "Setup de workflows",
      category: "Implementacion",
      price: 800,
      duration_minutes: 60,
      active: true,
    },
    {
      id: "svc-cleaning",
      created_at: now,
      updated_at: now,
      business_id: DEMO_BUSINESS_ID,
      name: "Limpieza dental",
      category: "Preventivo",
      price: 90,
      duration_minutes: 45,
      active: true,
    },
    {
      id: "svc-orthodontics",
      created_at: now,
      updated_at: now,
      business_id: DEMO_BUSINESS_ID,
      name: "Evaluacion de ortodoncia",
      category: "Especialidad",
      price: 140,
      duration_minutes: 60,
      active: true,
    },
    {
      id: "svc-treatment-follow-up",
      created_at: now,
      updated_at: now,
      business_id: DEMO_BUSINESS_ID,
      name: "Seguimiento de tratamiento",
      category: "Seguimiento",
      price: 75,
      duration_minutes: 30,
      active: true,
    },
    {
      id: "svc-emergency",
      created_at: now,
      updated_at: now,
      business_id: DEMO_BUSINESS_ID,
      name: "Consulta de urgencia",
      category: "Urgencias",
      price: 110,
      duration_minutes: 30,
      active: true,
    },
    {
      id: "svc-admissions",
      created_at: now,
      updated_at: now,
      business_id: "biz-university-demo",
      name: "Entrevista de admisión",
      category: "Admisiones",
      price: 0,
      duration_minutes: 30,
      active: true,
    },
    {
      id: "svc-scholarship",
      created_at: now,
      updated_at: now,
      business_id: "biz-university-demo",
      name: "Revisión de becas",
      category: "Financiamiento",
      price: 0,
      duration_minutes: 45,
      active: true,
    },
    {
      id: "svc-advising",
      created_at: now,
      updated_at: now,
      business_id: "biz-university-demo",
      name: "Asesoría académica",
      category: "Académico",
      price: 0,
      duration_minutes: 30,
      active: true,
    },
    {
      id: "svc-table",
      created_at: now,
      updated_at: now,
      business_id: "biz-food-demo",
      name: "Reserva de mesa",
      category: "Reservas",
      price: 0,
      duration_minutes: 90,
      active: true,
    },
    {
      id: "svc-corporate-order",
      created_at: now,
      updated_at: now,
      business_id: "biz-food-demo",
      name: "Pedido corporativo",
      category: "Pedidos",
      price: 350,
      duration_minutes: 45,
      active: true,
    },
    {
      id: "svc-private-event",
      created_at: now,
      updated_at: now,
      business_id: "biz-food-demo",
      name: "Evento privado",
      category: "Eventos",
      price: 1600,
      duration_minutes: 120,
      active: true,
    },
  ],
  appointments: [
    {
      id: "apt-zqx-dental-demo",
      created_at: now,
      updated_at: now,
      business_id: ZQX_BUSINESS_ID,
      client_id: "cli-zqx-dental-smile",
      service_id: "svc-zqx-dental-blueprint",
      title: "Revisión de plataforma dental",
      scheduled_at: "2026-04-30T16:00:00.000Z",
      status: "confirmed",
      location: "Meet",
      notes: "Validar agenda, intake y recordatorios.",
    },
    {
      id: "apt-cleaning",
      created_at: now,
      updated_at: now,
      business_id: DEMO_BUSINESS_ID,
      client_id: "cli-maria-lopez",
      service_id: "svc-cleaning",
      title: "Limpieza dental",
      scheduled_at: "2026-04-29T15:00:00.000Z",
      status: "confirmed",
      location: "Sillón 2",
      notes: "Confirmar seguro antes de la visita.",
    },
    {
      id: "apt-orthodontics",
      created_at: now,
      updated_at: now,
      business_id: DEMO_BUSINESS_ID,
      client_id: "cli-carlos-herrera",
      service_id: "svc-orthodontics",
      title: "Evaluacion de ortodoncia",
      scheduled_at: "2026-04-30T17:00:00.000Z",
      status: "pending",
      location: "Sillón 1",
      notes: "Enviar formulario de intake.",
    },
    {
      id: "apt-emergency",
      created_at: now,
      updated_at: now,
      business_id: DEMO_BUSINESS_ID,
      client_id: "cli-sofia-mendez",
      service_id: "svc-emergency",
      title: "Consulta de urgencia",
      scheduled_at: "2026-04-29T20:00:00.000Z",
      status: "pending",
      location: "Sillón 3",
      notes: "Prioridad alta por dolor.",
    },
    {
      id: "apt-admissions",
      created_at: now,
      updated_at: now,
      business_id: "biz-university-demo",
      client_id: "cli-university-demo",
      service_id: "svc-admissions",
      title: "Entrevista de admisión",
      scheduled_at: "2026-05-01T16:00:00.000Z",
      status: "pending",
      location: "Virtual",
      notes: "Enviar información de becas.",
    },
    {
      id: "apt-scholarship",
      created_at: now,
      updated_at: now,
      business_id: "biz-university-demo",
      client_id: "cli-university-luis",
      service_id: "svc-scholarship",
      title: "Revisión de becas",
      scheduled_at: "2026-04-30T18:00:00.000Z",
      status: "confirmed",
      location: "Oficina de admisiones",
      notes: "Revisar documentos financieros.",
    },
    {
      id: "apt-food-table",
      created_at: now,
      updated_at: now,
      business_id: "biz-food-demo",
      client_id: "cli-food-andrea",
      service_id: "svc-table",
      title: "Reserva de mesa",
      scheduled_at: "2026-04-29T23:30:00.000Z",
      status: "confirmed",
      location: "Salón principal",
      notes: "Mesa cerca de ventana.",
    },
    {
      id: "apt-food-event",
      created_at: now,
      updated_at: now,
      business_id: "biz-food-demo",
      client_id: "cli-food-corp",
      service_id: "svc-private-event",
      title: "Cotización de evento privado",
      scheduled_at: "2026-05-02T17:00:00.000Z",
      status: "pending",
      location: "Llamada",
      notes: "Enviar tres opciones de menú.",
    },
  ],
  followups: [
    {
      id: "flw-zqx-dental-demo",
      created_at: now,
      updated_at: now,
      business_id: ZQX_BUSINESS_ID,
      client_id: "cli-zqx-dental-smile",
      appointment_id: "apt-zqx-dental-demo",
      title: "Preparar presentación dental",
      channel: "meeting",
      due_at: "2026-04-30T12:00:00.000Z",
      status: "in_progress",
      owner: "gvcotto@zqxconsulting.com",
      notes: "Mostrar agenda, pacientes, recordatorios y admin multiempresa.",
    },
    {
      id: "flw-insurance",
      created_at: now,
      updated_at: now,
      business_id: DEMO_BUSINESS_ID,
      client_id: "cli-maria-lopez",
      appointment_id: "apt-cleaning",
      title: "Confirmar seguro",
      channel: "whatsapp",
      due_at: "2026-04-29T12:00:00.000Z",
      status: "open",
      owner: "admin@dentalsmile.example",
      notes: "Solicitar foto del seguro.",
    },
    {
      id: "flw-financing",
      created_at: now,
      updated_at: now,
      business_id: DEMO_BUSINESS_ID,
      client_id: "cli-carlos-herrera",
      appointment_id: "apt-orthodontics",
      title: "Enviar opciones de financiamiento",
      channel: "email",
      due_at: "2026-04-30T14:00:00.000Z",
      status: "in_progress",
      owner: "admin@dentalsmile.example",
      notes: "Incluir estimado de plan de pagos.",
    },
    {
      id: "flw-recall",
      created_at: now,
      updated_at: now,
      business_id: DEMO_BUSINESS_ID,
      client_id: "cli-maria-lopez",
      appointment_id: "apt-cleaning",
      title: "Recall preventivo 6 meses",
      channel: "whatsapp",
      due_at: "2026-10-29T15:00:00.000Z",
      status: "open",
      owner: "admin@dentalsmile.example",
      notes: "Automatizar invitación a limpieza semestral.",
    },
    {
      id: "flw-food-menu",
      created_at: now,
      updated_at: now,
      business_id: "biz-food-demo",
      client_id: "cli-food-corp",
      appointment_id: "apt-food-event",
      title: "Enviar propuesta de menú",
      channel: "email",
      due_at: "2026-04-30T17:00:00.000Z",
      status: "open",
      owner: "reservas@mesacentral.example",
      notes: "Tres opciones de menú para 35 personas.",
    },
  ],
  payments: [
    {
      id: "pay-zqx-blueprint",
      created_at: now,
      updated_at: now,
      business_id: ZQX_BUSINESS_ID,
      client_id: "cli-zqx-dental-smile",
      service_id: "svc-zqx-dental-blueprint",
      appointment_id: "apt-zqx-dental-demo",
      amount: 1200,
      amount_paid: 600,
      currency: "USD",
      status: "partial",
      due_at: "2026-05-03T16:00:00.000Z",
      description: "Blueprint dental CRM",
    },
    {
      id: "pay-cleaning",
      created_at: now,
      updated_at: now,
      business_id: DEMO_BUSINESS_ID,
      client_id: "cli-maria-lopez",
      service_id: "svc-cleaning",
      appointment_id: "apt-cleaning",
      amount: 90,
      amount_paid: 90,
      currency: "USD",
      status: "paid",
      due_at: "2026-04-29T15:00:00.000Z",
      paid_at: "2026-04-29T13:15:00.000Z",
      description: "Limpieza dental",
    },
    {
      id: "pay-orthodontics",
      created_at: now,
      updated_at: now,
      business_id: DEMO_BUSINESS_ID,
      client_id: "cli-carlos-herrera",
      service_id: "svc-orthodontics",
      appointment_id: "apt-orthodontics",
      amount: 140,
      amount_paid: 70,
      currency: "USD",
      status: "partial",
      due_at: "2026-04-30T17:00:00.000Z",
      description: "Evaluacion de ortodoncia",
    },
    {
      id: "pay-food-event",
      created_at: now,
      updated_at: now,
      business_id: "biz-food-demo",
      client_id: "cli-food-corp",
      service_id: "svc-private-event",
      appointment_id: "apt-food-event",
      amount: 1600,
      amount_paid: 0,
      currency: "USD",
      status: "pending",
      due_at: "2026-05-02T17:00:00.000Z",
      description: "Evento privado",
    },
  ],
  faqs: [
    {
      id: "faq-zqx-admin",
      created_at: now,
      updated_at: now,
      business_id: ZQX_BUSINESS_ID,
      question: "¿Cómo separo la administración ZQX de las empresas cliente?",
      answer: "El usuario gvcotto@zqxconsulting.com entra como zqx_owner, ve el selector de empresas, activa módulos y administra espacios de trabajo sin mezclar la operación diaria de cada empresa.",
      tags: ["admin", "empresas", "zqx"],
    },
    {
      id: "faq-dental-module",
      created_at: now,
      updated_at: now,
      business_id: DEMO_BUSINESS_ID,
      question: "¿Qué incluye el módulo dental?",
      answer: "Incluye pacientes, intake, agenda por disponibilidad, recordatorios 48-24-1, recalls de 6 meses, pagos y solicitudes de review.",
      tags: ["dentist", "dental", "patients", "agenda"],
    },
    {
      id: "faq-dental-reminders",
      created_at: now,
      updated_at: now,
      business_id: DEMO_BUSINESS_ID,
      question: "¿Cómo se reducen los no-shows?",
      answer: "La plataforma coordina recordatorios por WhatsApp, SMS o email con secuencia 48-24-1 horas y tareas de confirmación para recepción.",
      tags: ["reminders", "no-show", "whatsapp"],
    },
    {
      id: "faq-payments",
      created_at: now,
      updated_at: now,
      business_id: DEMO_BUSINESS_ID,
      question: "Puede controlar saldos pendientes?",
      answer: "Sí. Los pagos pueden estar pagados, pendientes o parciales, y el dashboard calcula el balance pendiente por paciente.",
      tags: ["payments", "balance", "accounts"],
    },
    {
      id: "faq-food-reservations",
      created_at: now,
      updated_at: now,
      business_id: "biz-food-demo",
      question: "¿Cómo funciona el módulo de comida?",
      answer: "Permite manejar reservas, pedidos corporativos, eventos, seguimientos y cobros desde la misma estructura CRM.",
      tags: ["food", "restaurant", "reservas"],
    },
  ],
  chatbot_logs: [],
};
